name: Run script
description: Test

inputs:
  env:
    description: env

outputs:
  token:
    description: token
    value: ${{ steps.result.outputs.token }}

runs:
  using: composite
  steps:
    - name: Define rule
      shell: bash
      run: |
        chmod +x ./.github/scripts/define-arn-rule.sh
        RULE=$(./.github/scripts/define-arn-rule.sh ${{ inputs.env }})
        echo "Rule is $RULE"

    - name: Run script
      id: result
      shell: bash
      run: |
        chmod +x ./.github/scripts/check-env.sh
        source ./.github/scripts/check-env.sh
        echo "go > $HIDDEN_SERVICE"
        echo "arg1 > $ARG1"
        echo "arg2 > $ARG2"