name: Run script
description: Test

runs:
  using: composite
  steps:
    - name: Run script
      shell: bash
      run: |
        chmod +x ./.github/scripts/check-env.sh
        TOKEN=$(./.github/scripts/check-env.sh)
        echo "go > $HIDDEN_SERVICE"
        echo "token=$TOKEN" >> $GITHUB_OUTPUT