name: Run script
description: Test

outputs:
  token:
    description: token
    value: ${{ steps.result.outputs.token }}

runs:
  using: composite
  steps:
    - name: Run script
      id: result
      shell: bash
      run: |
        chmod +x ./.github/scripts/check-env.sh
        TOKEN=$(./.github/scripts/check-env.sh)
        echo "go > $TOKEN"
        echo "token=$TOKEN" >> $GITHUB_OUTPUT