name: Deploy DEV

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        default: '2'
        required: true
        description: "Deploy dev-"
        options:
          - 'eval'
          - 'prod'
          - 'eu'
  # push:
  #   branches:
  #     - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.target || 'prod' }}
    
    steps:

      - uses: actions/checkout@v2

      # - name: Run script
      #   id: check
      #   uses: ./.github/actions/check-service
      #   with:
      #     env: ${{ env.ENV }}

      # - name: Report
      #   shell: bash
      #   run: echo "${{steps.check.outputs.token}}"

      - name: Load artifacts
        uses: actions/download-artifact@v2
        with:
          name: release-docker-image
          path: artifacts

      - name: Pull image
        shell: bash
        run: |
          docker load artifacts/release-image.tag
          docker pull consul-update2
