name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run test and lint
        run: echo "test"

      - name: Checkout to sandbox branch
        run: |
          git checkout -b sandbox

      - name: Push to sandbox
        run: |
          git add .
          git commit -m "${{ github.run_number }}"
          git push origin sandbox
